name: 工厂

on:
    workflow_dispatch:
    schedule:
        - cron: "0 */1 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_dreamFactory

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
           
